import { AdminModulePage } from "./module-page";
import { categories } from "@/data/categories";
import { collections } from "@/data/collections";

type Kind = "categories"|"collections"|"orders"|"reservations"|"clients"|"promotions"|"messages"|"content";
const configurations: Record<Kind,{eyebrow:string;title:string;intro:string;metrics:Array<[string,string]>;rows:Array<Array<string>>;actionLabel?:string;actionHref?:string}>={
  categories:{eyebrow:"Organisation",title:"Catégories",intro:"Gérez l’arborescence multi-niveaux, les périodes et les filtres propres à chaque univers.",metrics:[["Catégories principales","3"],["Sous-catégories",String(categories.reduce((n,c)=>n+c.subcategories.length,0))],["Niveaux possibles","Illimités"]],rows:categories.map(c=>[c.name,`${c.subcategories.length} sous-catégories`,`${c.periods.length} périodes`]),actionLabel:"Ajouter une catégorie",actionHref:"/admin/categories?nouveau=1"},
  collections:{eyebrow:"Ensembles",title:"Collections",intro:"Regroupez les objets par artiste, atelier, marque, territoire, thème ou période.",metrics:[["Collections",String(collections.length)],["Mises en avant",String(collections.filter(c=>c.featured).length)],["Objets associés",String(new Set(collections.flatMap(c=>c.productIds)).size)]],rows:collections.map(c=>[c.name,c.period,`${c.productIds.length} objets`]),actionLabel:"Créer une collection",actionHref:"/admin/collections?nouveau=1"},
  orders:{eyebrow:"Ventes",title:"Commandes",intro:"Suivez les paiements, préparations, expéditions, retours et remboursements.",metrics:[["À préparer","3"],["Expédiées ce mois","9"],["Panier moyen","174 €"]],rows:[["INV-260715-04","Camille Roche","À préparer"],["INV-260714-09","Arthur Martin","Expédiée"],["INV-260713-02","Lina Bernard","Payée"],["INV-260710-11","Noah Petit","Livrée"]]},
  reservations:{eyebrow:"Objets uniques",title:"Réservations",intro:"Acceptez, refusez ou prolongez les demandes et surveillez leurs échéances.",metrics:[["En attente","2"],["Actives","3"],["Expirent aujourd’hui","1"]],rows:[["Vase corolle Vallauris","Jeanne Laurent","Expire dans 4 h"],["Programme Bol d’Or 1973","Sami Vidal","À examiner"],["Carte Marseille Vieux-Port","Alice Moreau","Active"]]},
  clients:{eyebrow:"Relation client",title:"Clients",intro:"Retrouvez les coordonnées, commandes, réservations et demandes de retour.",metrics:[["Clients","86"],["Nouveaux ce mois","4"],["Clients récurrents","28 %"]],rows:[["Camille Roche","camille@example.fr","3 commandes"],["Arthur Martin","arthur@example.fr","1 commande"],["Lina Bernard","lina@example.fr","2 commandes"]]},
  promotions:{eyebrow:"Prix",title:"Codes promotionnels",intro:"Créez des remises limitées par date, montant minimum et nombre d’utilisations.",metrics:[["Codes actifs","1"],["Utilisations","7"],["Remises accordées","82 €"]],rows:[["INVENTAIRE10","−10 %","Actif"],["PORTOFFERT","Livraison offerte","Inactif"]],actionLabel:"Créer un code",actionHref:"/admin/promotions?nouveau=1"},
  messages:{eyebrow:"Boîte de réception",title:"Messages",intro:"Centralisez les questions, demandes de photos, offres et estimations de livraison.",metrics:[["Non lus","3"],["Réservations","2"],["Délai moyen","6 h"]],rows:[["Photos supplémentaires","Jeanne Laurent","Non lu"],["Livraison vers la Belgique","Mathieu Roy","À répondre"],["Proposition de collection","Sophie Blanc","Traité"]]},
  content:{eyebrow:"Éditorial",title:"Contenus du site",intro:"Pilotez les textes de l’accueil, les garanties, la FAQ et les pages légales.",metrics:[["Pages publiées","12"],["Brouillons","1"],["Dernière mise à jour","Aujourd’hui"]],rows:[["Page d’accueil","Publiée","Modifiée aujourd’hui"],["Conditions de vente","Publiée","15 juillet 2026"],["FAQ","Publiée","10 juillet 2026"],["Guide des états","Brouillon","8 juillet 2026"]]},
};
export function ModulePage({kind}:{kind:Kind}){return <AdminModulePage {...configurations[kind]}/>}
