import Link from "next/link";
import { ArrowRight, BadgeCheck, Clock3, PackageCheck, Search, ShieldCheck } from "lucide-react";
import { ProductGrid } from "@/components/catalogue/product-grid";
import { NewsletterForm } from "@/components/forms/newsletter-form";
import { DemoArtwork } from "@/components/ui/demo-artwork";
import { SectionHeading } from "@/components/ui/section-heading";
import { categories } from "@/data/categories";
import { collections } from "@/data/collections";
import { products } from "@/data/products";

export default function Home() {
  const featured = products.filter((product) => product.featured && product.published).slice(0,4);
  const rare = products.filter((product) => product.rareItem && product.published).slice(0,4);
  return <>
    <section className="container-page py-5 sm:py-7"><div className="relative isolate min-h-[38rem] overflow-hidden rounded-[1.75rem] bg-[#173f35] text-white sm:min-h-[42rem]"><div className="absolute inset-0 opacity-75"><DemoArtwork kind="COLLECTION" title="Objets et archives choisis" className="h-full w-full" priorityLabel="Collection en ligne" /></div><div className="absolute inset-0 bg-gradient-to-r from-[#102d26] via-[#173f35]/85 to-transparent"/><div className="relative flex min-h-[38rem] max-w-3xl flex-col justify-end p-7 sm:min-h-[42rem] sm:p-14 lg:p-20"><p className="eyebrow text-[#dec6a4]">Objets & archives · Collection privée</p><h1 className="mt-5 text-balance text-5xl leading-[.98] sm:text-7xl lg:text-[5.6rem]">Les objets passent.<br/>Leurs histoires restent.</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/75 sm:text-lg">Céramiques singulières, revues de passion et cartes postales anciennes, choisies et documentées une à une.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary bg-white text-[#173f35] hover:bg-[#e9dfd0]" href="/catalogue"><Search size={17}/>Explorer le catalogue</Link><Link className="btn-secondary border-white/30 bg-white/5 text-white hover:border-white hover:bg-white/10" href="/nouveautes">Voir les nouveautés <ArrowRight size={17}/></Link></div></div></div></section>
    <section className="container-page section-space"><SectionHeading eyebrow="Trois univers" title="Collectionner, c’est choisir ce que l’on transmet." description="Explorez le catalogue par matière, passion ou territoire."/><div className="grid gap-4 lg:grid-cols-3">{categories.map((category,index) => { const kind = category.slug === "ceramique" ? "CERAMIC" : category.slug === "revues-auto-moto" ? "MAGAZINE" : "POSTCARD"; return <Link href={`/${category.slug}`} key={category.id} className="group relative overflow-hidden rounded-[1.5rem] bg-stone-200"><DemoArtwork kind={kind} title={category.name} className="aspect-[4/5] sm:aspect-[5/4] lg:aspect-[4/5]"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/25 to-transparent p-7 pt-24 text-white"><p className="eyebrow text-white/65">0{index+1} · {category.subcategories.length} familles</p><h2 className="mt-3 text-3xl sm:text-4xl">{category.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/70">{category.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Découvrir <ArrowRight size={16} className="transition group-hover:translate-x-1"/></span></div></Link>; })}</div></section>
    <section className="border-y hairline bg-white/55"><div className="container-page section-space"><SectionHeading eyebrow="Dernières trouvailles" title="Nouveaux objets à l’inventaire" href="/nouveautes"/><ProductGrid products={featured}/></div></section>
    <section className="container-page section-space"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow text-[#a35f3f]">Le regard du vendeur</p><h2 className="mt-5 text-balance text-4xl leading-tight sm:text-6xl">Décrire sans embellir. Montrer sans cacher.</h2><p className="mt-6 max-w-xl leading-7 text-stone-600">L’état, les marques du temps, une restauration ou une attribution incertaine font partie de l’histoire d’un objet. Chaque fiche les indique clairement pour que vous puissiez choisir en confiance.</p><Link className="btn-secondary mt-7" href="/a-propos">Découvrir notre démarche <ArrowRight size={16}/></Link></div><div className="grid grid-cols-2 gap-3"><DemoArtwork kind="CERAMIC" title="Examen d'une céramique" className="aspect-[4/5] rounded-2xl"/><DemoArtwork kind="POSTCARD" title="Documentation d'une archive" className="mt-10 aspect-[4/5] rounded-2xl"/></div></div></section>
    <section className="bg-[#dfd2bf]/55"><div className="container-page section-space"><SectionHeading eyebrow="Pièces singulières" title="Rares, parfois uniques" description="Des objets peu courants dont la disponibilité peut être brève." href="/objets-rares"/><ProductGrid products={rare}/></div></section>
    <section className="container-page section-space"><SectionHeading eyebrow="Ensembles documentés" title="Collections du moment" href="/collections"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{collections.filter((collection)=>collection.featured).slice(0,3).map((collection)=><Link key={collection.id} href={`/collections/${collection.slug}`} className="group surface overflow-hidden"><DemoArtwork kind="COLLECTION" title={collection.name} className="aspect-[16/9]"/><div className="p-6"><p className="eyebrow text-[#a35f3f]">{collection.period}</p><h3 className="mt-3 text-2xl">{collection.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-stone-600">{collection.description}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#173f35]">Voir les {collection.productIds.length} objets <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></div></Link>)}</div></section>
    <section className="border-y hairline bg-white/65"><div className="container-page grid gap-px py-1 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck,"Objets documentés","Description précise, défauts inclus"],[ShieldCheck,"Paiement sécurisé","Cartes traitées par Stripe"],[PackageCheck,"Emballage adapté","Protection selon chaque matière"],[Clock3,"Réponse personnelle","Sous un jour ouvré"]].map(([Icon,title,text])=>{const I=Icon as typeof BadgeCheck;return <div className="p-6" key={String(title)}><I size={23} className="text-[#173f35]"/><h2 className="mt-4 font-sans text-sm font-bold">{String(title)}</h2><p className="mt-1 text-xs leading-5 text-stone-500">{String(text)}</p></div>})}</div></section>
    <section className="container-page py-8 sm:py-12"><div className="rounded-[1.75rem] bg-[#173f35] px-6 py-12 text-white sm:px-12 lg:flex lg:items-center lg:justify-between lg:gap-16"><div><p className="eyebrow text-[#dec6a4]">Le carnet de L’Inventaire</p><h2 className="mt-4 text-3xl sm:text-4xl">Les nouvelles pièces, sans bruit.</h2><p className="mt-3 text-sm text-white/65">Un message occasionnel pour découvrir les derniers objets et collections.</p></div><div className="mt-7 lg:mt-0 lg:w-[28rem]"><NewsletterForm/></div></div></section>
  </>;
}
