"use client";

import Link from "next/link";
import { ArrowLeft, CreditCard, LoaderCircle, LockKeyhole, PackageOpen, ShieldCheck, Truck } from "lucide-react";
import { useMemo, useState } from "react";
import { useShop } from "@/components/providers/shop-provider";
import { products } from "@/data/products";
import { formatPrice } from "@/lib/site";

export function CheckoutPageClient(){
  const {cart}=useShop(); const [sending,setSending]=useState(false); const [error,setError]=useState("");
  const lines=useMemo(()=>cart.flatMap((line)=>{const product=products.find((p)=>p.id===line.productId);return product?[{...line,product}]:[]}),[cart]);
  const subtotal=lines.reduce((sum,line)=>sum+line.product.price*line.quantity,0); const shipping=lines.length?Math.max(...lines.map((l)=>l.product.shippingPrice)):0; const total=subtotal+shipping;
  if(!lines.length)return <section className="container-page grid min-h-[65vh] place-items-center py-20 text-center"><div><PackageOpen className="mx-auto text-[#173f35]" size={42}/><h1 className="mt-5 text-5xl">Aucune commande à finaliser</h1><p className="mt-4 text-stone-600">Ajoutez d’abord un objet disponible à votre panier.</p><Link className="btn-primary mt-7" href="/catalogue">Retour au catalogue</Link></div></section>;
  return <section className="container-page py-9 sm:py-14"><Link href="/panier" className="inline-flex items-center gap-2 text-xs font-bold text-stone-600 hover:text-[#173f35]"><ArrowLeft size={15}/>Retour au panier</Link><div className="mt-8 grid items-start gap-10 lg:grid-cols-[1fr_23rem] lg:gap-16"><div><p className="eyebrow text-[#a35f3f]">Commande sécurisée</p><h1 className="mt-4 text-5xl sm:text-6xl">Finaliser la commande</h1><form id="checkout-form" className="mt-10 space-y-9" onSubmit={async(event)=>{event.preventDefault();setSending(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({items:cart,customerEmail:String(form.get("email")),shippingMethod:String(form.get("shippingMethod"))})});const body=await response.json() as {url?:string;message?:string};if(!response.ok||!body.url)throw new Error(body.message??"La commande n’a pas pu être créée.");window.location.assign(body.url);}catch(cause){setError(cause instanceof Error?cause.message:"La commande n’a pas pu être créée.");setSending(false)}}}>
        <CheckoutSection number="1" title="Vos coordonnées"><div className="grid gap-4 sm:grid-cols-2"><Field id="firstName" label="Prénom" required/><Field id="lastName" label="Nom" required/></div><Field id="email" label="Adresse e-mail" type="email" required/><Field id="phone" label="Téléphone" type="tel" required/></CheckoutSection>
        <CheckoutSection number="2" title="Adresse de livraison"><Field id="street" label="Adresse" required/><div className="grid gap-4 sm:grid-cols-[9rem_1fr]"><Field id="postalCode" label="Code postal" required/><Field id="city" label="Ville" required/></div><div><label className="mb-1.5 block text-sm font-semibold" htmlFor="country">Pays</label><select id="country" name="country" className="field" defaultValue="FR"><option value="FR">France</option><option value="BE">Belgique</option><option value="DE">Allemagne</option><option value="ES">Espagne</option><option value="IT">Italie</option></select></div><label className="flex items-start gap-3 text-sm"><input className="mt-1 accent-[#173f35]" type="checkbox" name="billingSame" defaultChecked/>Utiliser cette adresse pour la facturation</label></CheckoutSection>
        <CheckoutSection number="3" title="Mode de livraison"><label className="flex cursor-pointer items-start gap-4 rounded-xl border-2 border-[#173f35] bg-emerald-50/45 p-4"><input className="mt-1 accent-[#173f35]" type="radio" name="shippingMethod" value="tracked" defaultChecked/><Truck className="shrink-0 text-[#173f35]"/><span className="flex-1"><strong className="block text-sm">Livraison suivie et assurée</strong><span className="mt-1 block text-xs leading-5 text-stone-600">Emballage adapté, suivi transmis par e-mail.</span></span><strong className="text-sm">{formatPrice(shipping)}</strong></label></CheckoutSection>
        <CheckoutSection number="4" title="Paiement"><div className="flex items-start gap-4 rounded-xl border hairline bg-white p-5"><CreditCard className="shrink-0 text-[#173f35]"/><div><p className="text-sm font-bold">Carte bancaire avec Stripe</p><p className="mt-1 text-xs leading-5 text-stone-500">Vous serez dirigé vers la page de paiement sécurisée. En mode démonstration, aucun débit n’est effectué.</p></div></div></CheckoutSection>
        {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>}
      </form></div><aside className="surface sticky top-32 p-6"><h2 className="font-sans text-base font-bold">Votre commande</h2><div className="mt-5 space-y-4">{lines.map(({product})=><div className="flex justify-between gap-4 text-sm" key={product.id}><div><p className="font-semibold leading-5">{product.name}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-stone-500">{product.reference}</p></div><p className="shrink-0">{formatPrice(product.price)}</p></div>)}</div><dl className="mt-6 space-y-3 border-t hairline pt-5 text-sm"><div className="flex justify-between"><dt className="text-stone-600">Sous-total</dt><dd>{formatPrice(subtotal)}</dd></div><div className="flex justify-between"><dt className="text-stone-600">Livraison</dt><dd>{formatPrice(shipping)}</dd></div><div className="flex justify-between border-t hairline pt-4 text-lg font-bold"><dt>Total</dt><dd>{formatPrice(total)}</dd></div></dl><button form="checkout-form" className="btn-primary mt-6 w-full" disabled={sending}>{sending?<LoaderCircle className="animate-spin" size={17}/>:<LockKeyhole size={17}/>} {sending?"Préparation…":"Payer la commande"}</button><p className="mt-4 flex items-start gap-2 text-[11px] leading-5 text-stone-500"><ShieldCheck className="mt-0.5 shrink-0" size={14}/>Le prix et la disponibilité sont vérifiés à nouveau côté serveur avant le paiement.</p></aside></div></section>;
}

function CheckoutSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <fieldset className="surface p-6 sm:p-8"><legend className="flex items-center gap-3 px-2 text-lg font-bold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#173f35] text-xs text-white">{number}</span>{title}</legend><div className="mt-5 grid gap-4">{children}</div></fieldset>}
function Field({id,label,type="text",required=false}:{id:string;label:string;type?:string;required?:boolean}){return <div><label className="mb-1.5 block text-sm font-semibold" htmlFor={id}>{label}</label><input className="field" id={id} name={id} type={type} required={required}/></div>}
