import type { Metadata } from "next";
import Link from "next/link";
import { Archive, Eye, HandHeart, PackageCheck } from "lucide-react";
import { DemoArtwork } from "@/components/ui/demo-artwork";

export const metadata: Metadata = { title: "À propos", description: "Découvrez l’histoire et les engagements de L’Inventaire." };

export default function AboutPage() {
  return <><section className="container-page grid items-center gap-10 py-12 lg:grid-cols-2 lg:py-20"><div><p className="eyebrow text-[#a35f3f]">Notre histoire</p><h1 className="mt-5 text-balance text-5xl leading-[1.02] sm:text-7xl">Une boutique pensée comme un inventaire vivant.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Derrière chaque objet, il y a une main, un lieu et une époque. Notre rôle est de les documenter, de les préserver et de les transmettre sans les dénaturer.</p><Link className="btn-primary mt-8" href="/catalogue">Explorer le catalogue</Link></div><DemoArtwork kind="COLLECTION" title="L'atelier de L'Inventaire" className="aspect-[5/4] rounded-[2rem]" /></section><section className="bg-[#173f35] text-white"><div className="container-page grid gap-px py-1 md:grid-cols-4">{[[Eye,"Regard précis","Chaque pièce est examinée et décrite honnêtement."],[Archive,"Documentation","Dates, provenance et défauts sont consignés avec soin."],[PackageCheck,"Expédition soignée","Emballage adapté à la fragilité et suivi systématique."],[HandHeart,"Relation directe","Une question ? Vous échangez avec la personne qui connaît l’objet."]].map(([Icon,title,text]) => { const I = Icon as typeof Eye; return <div className="border-white/10 p-7 md:border-r" key={String(title)}><I size={24} className="text-[#d9bd94]"/><h2 className="mt-5 font-sans text-sm font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-white/65">{String(text)}</p></div>; })}</div></section><section className="container-page section-space text-center"><p className="eyebrow text-[#a35f3f]">La sélection</p><h2 className="mx-auto mt-4 max-w-3xl text-balance text-4xl sm:text-6xl">Peu d’objets, mais chacun a quelque chose à raconter.</h2><p className="mx-auto mt-6 max-w-2xl leading-7 text-stone-600">Le catalogue évolue au fil des trouvailles. Les objets vendus restent visibles pour préserver la mémoire des collections et aider les passionnés dans leurs recherches.</p></section></>;
}
