"use client";

import Link from "next/link";
import { CheckCircle2, Eye, EyeOff, LoaderCircle, LockKeyhole } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useState } from "react";

export function LoginForm(){const params=useSearchParams();const[show,setShow]=useState(false);const[state,setState]=useState<"idle"|"sending"|"error">("idle");const[message,setMessage]=useState("");return <form className="grid gap-5" onSubmit={async(e)=>{e.preventDefault();setState("sending");setMessage("");const form=new FormData(e.currentTarget);try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});const body=await response.json() as {error?:{message?:string};message?:string};if(!response.ok)throw new Error(body.error?.message??body.message??"Connexion impossible.");const callback=params.get("callbackUrl");window.location.assign(callback?.startsWith("/")?callback:"/compte");}catch(cause){setState("error");setMessage(cause instanceof Error?cause.message:"Connexion impossible.")}}}><AuthField id="login-email" name="email" label="Adresse e-mail" type="email" autoComplete="email"/><div><div className="mb-1.5 flex items-center justify-between"><label className="text-sm font-semibold" htmlFor="login-password">Mot de passe</label><Link className="text-xs font-semibold text-[#173f35] hover:underline" href="/mot-de-passe-oublie">Mot de passe oublié ?</Link></div><div className="relative"><input className="field pr-12" id="login-password" name="password" type={show?"text":"password"} autoComplete="current-password" required/><button type="button" className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full p-2 text-stone-500" onClick={()=>setShow(v=>!v)} aria-label={show?"Masquer le mot de passe":"Afficher le mot de passe"}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>{state==="error"&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{message}</p>}<button className="btn-primary w-full" disabled={state==="sending"}>{state==="sending"?<LoaderCircle className="animate-spin" size={17}/>:<LockKeyhole size={17}/>}Se connecter</button></form>}

export function RegisterForm(){const[state,setState]=useState<"idle"|"sending"|"sent"|"error">("idle");const[message,setMessage]=useState("");if(state==="sent")return <div className="text-center"><CheckCircle2 className="mx-auto text-emerald-700" size={40}/><h2 className="mt-5 text-3xl">Compte prêt à être activé</h2><p className="mt-3 text-sm leading-6 text-stone-600">En mode démonstration, aucune donnée n’est conservée. Avec PostgreSQL configuré, un e-mail de confirmation sera envoyé.</p><Link className="btn-primary mt-7" href="/connexion">Aller à la connexion</Link></div>;return <form className="grid gap-5" onSubmit={async(e)=>{e.preventDefault();setState("sending");setMessage("");const form=new FormData(e.currentTarget);const password=String(form.get("password"));if(password!==form.get("confirmation")){setState("error");setMessage("Les deux mots de passe ne correspondent pas.");return}try{const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:form.get("firstName"),lastName:form.get("lastName"),email:form.get("email"),phone:form.get("phone"),password,acceptTerms:form.get("terms")})});const body=await response.json() as {error?:{message?:string};message?:string};if(!response.ok)throw new Error(body.error?.message??body.message??"Création impossible.");setState("sent")}catch(cause){setState("error");setMessage(cause instanceof Error?cause.message:"Création impossible.")}}}><div className="grid gap-4 sm:grid-cols-2"><AuthField id="register-firstName" name="firstName" label="Prénom"/><AuthField id="register-lastName" name="lastName" label="Nom"/></div><AuthField id="register-email" name="email" label="Adresse e-mail" type="email" autoComplete="email"/><AuthField id="register-phone" name="phone" label="Téléphone (facultatif)" type="tel"/><AuthField id="register-password" name="password" label="Mot de passe" type="password" autoComplete="new-password" help="12 caractères minimum, avec majuscule, minuscule et chiffre."/><AuthField id="register-confirmation" name="confirmation" label="Confirmer le mot de passe" type="password" autoComplete="new-password"/><label className="flex items-start gap-3 text-xs leading-5 text-stone-600"><input className="mt-1 accent-[#173f35]" type="checkbox" name="terms" required/>J’accepte les <Link href="/cgv" className="font-semibold underline">conditions générales de vente</Link> et la <Link href="/confidentialite" className="font-semibold underline">politique de confidentialité</Link>.</label>{state==="error"&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{message}</p>}<button className="btn-primary w-full" disabled={state==="sending"}>{state==="sending"&&<LoaderCircle className="animate-spin" size={17}/>}Créer mon compte</button></form>}

export function ForgotPasswordForm(){const[sent,setSent]=useState(false);if(sent)return <div className="text-center"><CheckCircle2 className="mx-auto text-emerald-700" size={40}/><h2 className="mt-5 text-3xl">Consultez votre messagerie</h2><p className="mt-3 text-sm leading-6 text-stone-600">Si un compte correspond à cette adresse, vous recevrez les instructions de réinitialisation.</p><Link className="btn-secondary mt-7" href="/connexion">Retour à la connexion</Link></div>;return <form className="grid gap-5" onSubmit={(e)=>{e.preventDefault();setSent(true)}}><AuthField id="forgot-email" name="email" label="Adresse e-mail" type="email" autoComplete="email"/><button className="btn-primary">Envoyer le lien</button></form>}

function AuthField({id,name,label,type="text",autoComplete,help}:{id:string;name:string;label:string;type?:string;autoComplete?:string;help?:string}){return <div><label className="mb-1.5 block text-sm font-semibold" htmlFor={id}>{label}</label><input className="field" id={id} name={name} type={type} autoComplete={autoComplete} required={label.indexOf("facultatif")<0}/>{help&&<p className="mt-1.5 text-[11px] leading-4 text-stone-500">{help}</p>}</div>}
